import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { DuckDBDatabase, DuckDBTable } from "@/lib/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Download } from "lucide-react";
import { toast } from "sonner";

export function Exports() { const [dbs, setDbs] = useState<DuckDBDatabase[]>([]); const [tables, setTables] = useState<DuckDBTable[]>([]); const [db, setDb] = useState(""); const [table, setTable] = useState(""); useEffect(() => { api.duckdbDatabases().then(setDbs).catch(() => {}); }, []); const choose = (value: string) => { setDb(value); setTable(""); api.duckdbTables(value).then((x) => setTables(x.tables)).catch(() => setTables([])); }; const exportIt = async (format: string) => { try { const result = await api.exportTable(db, table, format); toast.success(`Exported ${result.rows} rows to ${result.path}`); } catch (e) { toast.error(String(e)); } }; return <div className="mx-auto max-w-3xl space-y-6 p-8"><div><h1 className="text-2xl font-semibold tracking-tight">Exports</h1><p className="text-sm text-muted-foreground">DuckDB remains canonical. Export selected tables to portable formats when needed.</p></div><Card><CardHeader><CardTitle className="text-base">Export DuckDB table</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-1"><Label>Database</Label><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={db} onChange={(e) => choose(e.target.value)}><option value="">Select database</option>{dbs.map((x) => <option key={x.id} value={x.path}>{x.name}</option>)}</select></div><div className="space-y-1"><Label>Table</Label><select className="w-full rounded-md border bg-background px-3 py-2 text-sm" value={table} onChange={(e) => setTable(e.target.value)}><option value="">Select table</option>{tables.map((x) => <option key={x.name}>{x.name}</option>)}</select></div><div className="flex flex-wrap gap-2">{["csv", "parquet", "sqlite", "json"].map((format) => <Button key={format} variant="outline" disabled={!db || !table} onClick={() => exportIt(format)}><Download className="mr-1 h-4 w-4" /> {format.toUpperCase()}</Button>)}</div></CardContent></Card></div>; }
